#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export LSCOLORS=FxfxcxdxbxGxDxabagacad

# Editor
if type "vim" > /dev/null 2>&1; then
  export EDITOR="vim"
fi

# Inform gpg-agent of the current TTY for user prompts.
# If you want to check gpg, type:
#   echo 'test' | gpg --clearsign
export GPG_TTY=$TTY

# rbenv
[[ -d $HOME/.rbenv ]] && \
  export PATH=${HOME}/.rbenv/bin:${PATH} && \
  eval "$(rbenv init -)"

# nodenv
if type "nodenv" > /dev/null 2>&1; then
  eval "$(nodenv init -)"
fi

# Open JDK
export PATH="/opt/homebrew/opt/openjdk/bin:$PATH"
export CPPFLAGS="-I/opt/homebrew/opt/openjdk/include"

# SPHINX
export PATH="$PATH:/opt/homebrew/opt/sphinx-doc/bin"

#
# Alias
#
alias tree='tree -a -I "\.DS_Store|\.git|\.vscode|node_modules|vendor\/bundle" -N'

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
